# We have a conf and classes directory, add to BBPATH
BBPATH .= ":${LAYERDIR}"

# We have recipes-* directories, add to BBFILES
BBFILES += "${LAYERDIR}/recipes-*/*/*.bb \
	${LAYERDIR}/recipes-*/*/*.bbappend"

BBFILE_COLLECTIONS += "rpi-labgrid-exporter"
BBFILE_PATTERN_rpi-labgrid-exporter = "^${LAYERDIR}/"
BBFILE_PRIORITY_rpi-labgrid-exporter = "8"

LAYERDEPENDS_rpi-labgrid-exporter = "core"
LAYERDEPENDS_rpi-labgrid-exporter += "meta-python"
LAYERDEPENDS_rpi-labgrid-exporter += "labgrid"
LAYERDEPENDS_rpi-labgrid-exporter += "networking-layer"

LAYERSERIES_COMPAT_rpi-labgrid-exporter = "scarthgap"
